# Generated by Django 2.1.5 on 2019-02-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.User')),
            ],
        ),

    ]
