# Generated by Django 2.1.5 on 2019-02-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.User')),
            ],
        ),
    ]
