# Generated by Django 2.1.5 on 2019-03-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0008_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.Record')),
            ],
        ),
    ]
