# Generated by Django 2.1.5 on 2019-03-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0011_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
